import JSON_DATA_ENV from "../../../config/config_env.json";
import PERMISSIONS_SPOTIFY from "./permissions.json";
const {
  SPOTIFY_AUTH,
  SPOTIFY_DEV_CLIENT_ID,
  SPOTIFY_DEV_SECRET,
  SPOTIFY_TOKEN,
  SPOTIFY_REDIRECT_URL,
  SPOTIFY_GETME_DATA_URL,
} = JSON_DATA_ENV.API;

export const REDIRECT_PROXY = JSON_DATA_ENV.PROXY.REDIRECT_PROXY;

export const SPOTIFY_ST = {
  SPOTIFY_AUTH,
  SPOTIFY_DEV_CLIENT_ID,
  SPOTIFY_DEV_SECRET,
  SPOTIFY_TOKEN,
  SPOTIFY_REDIRECT_URL,
  SPOTIFY_GETME_DATA_URL,
};

export const CLAIMS_SPOTIFY: string[] = Object.keys(
  new Object(PERMISSIONS_SPOTIFY)
);
